import colorama as C

RED = C.Fore.RED
YELLOW = C.Fore.YELLOW
GREEN = C.Fore.GREEN
BLUE = C.Fore.BLUE
CYAN = C.Fore.CYAN
MAGENTA = C.Fore.MAGENTA
WHITE = C.Fore.WHITE
BLACK = C.Fore.BLACK
LIGHTRED_EX = C.Fore.LIGHTRED_EX
LIGHTYELLOW_EX = C.Fore.LIGHTYELLOW_EX
LIGHTGREEN_EX = C.Fore.LIGHTGREEN_EX
LIGHTBLUE_EX = C.Fore.LIGHTBLUE_EX
LIGHTCYAN_EX = C.Fore.LIGHTCYAN_EX
LIGHTMAGENTA_EX = C.Fore.LIGHTMAGENTA_EX
LIGHTWHITE_EX = C.Fore.LIGHTWHITE_EX
LIGHTBLACK_EX = C.Fore.LIGHTBLACK_EX
BRIGHT_STYLE = C.Style.BRIGHT
NORMAL_STYLE = C.Style.NORMAL

RED_BG = C.Back.RED
YELLOW_BG = C.Back.YELLOW
GREEN_BG = C.Back.GREEN
BLUE_BG = C.Back.BLUE
CYAN_BG = C.Back.CYAN
MAGENTA_BG = C.Back.MAGENTA
WHITE_BG = C.Back.WHITE
BLACK_BG = C.Back.BLACK
LIGHTRED_EX_BG = C.Back.LIGHTRED_EX
LIGHTYELLOW_EX_BG = C.Back.LIGHTYELLOW_EX
LIGHTGREEN_EX_BG = C.Back.LIGHTGREEN_EX
LIGHTBLUE_EX_BG = C.Back.LIGHTBLUE_EX
LIGHTCYAN_EX_BG = C.Back.LIGHTCYAN_EX
LIGHTMAGENTA_EX_BG = C.Back.LIGHTMAGENTA_EX
LIGHTWHITE_EX_BG = C.Back.LIGHTWHITE_EX
LIGHTBLACK_EX_BG = C.Back.LIGHTBLACK_EX